# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Cdesc_comp', [dirname(__file__)])
        except ImportError:
            import _Cdesc_comp
            return _Cdesc_comp
        if fp is not None:
            try:
                _mod = imp.load_module('_Cdesc_comp', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Cdesc_comp = swig_import_helper()
    del swig_import_helper
else:
    import _Cdesc_comp
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Cdesc_comp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Cdesc_comp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Cdesc_comp, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _Cdesc_comp.new_Cdesc_comp()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _Cdesc_comp.delete_Cdesc_comp
    __del__ = lambda self : None;
    def equals(self, *args): return _Cdesc_comp.Cdesc_comp_equals(self, *args)
    def read_str(self, *args): return _Cdesc_comp.Cdesc_comp_read_str(self, *args)
    def __str__(self): return _Cdesc_comp.Cdesc_comp___str__(self)
    def pred(self, *args): return _Cdesc_comp.Cdesc_comp_pred(self, *args)
Cdesc_comp_swigregister = _Cdesc_comp.Cdesc_comp_swigregister
Cdesc_comp_swigregister(Cdesc_comp)



