# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Cmatrice', [dirname(__file__)])
        except ImportError:
            import _Cmatrice
            return _Cmatrice
        if fp is not None:
            try:
                _mod = imp.load_module('_Cmatrice', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Cmatrice = swig_import_helper()
    del swig_import_helper
else:
    import _Cmatrice
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Cmatrice(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Cmatrice, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Cmatrice, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _Cmatrice.new_Cmatrice()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _Cmatrice.delete_Cmatrice
    __del__ = lambda self : None;
    def carac(self, *args): return _Cmatrice.Cmatrice_carac(self, *args)
    def g_val(self, *args): return _Cmatrice.Cmatrice_g_val(self, *args)
    def exponentielle(self): return _Cmatrice.Cmatrice_exponentielle(self)
    def logarithme(self): return _Cmatrice.Cmatrice_logarithme(self)
    def log_normalise(self): return _Cmatrice.Cmatrice_log_normalise(self)
    def copy(self, *args): return _Cmatrice.Cmatrice_copy(self, *args)
    def melange(self): return _Cmatrice.Cmatrice_melange(self)
    def FB(self, *args): return _Cmatrice.Cmatrice_FB(self, *args)
    def forward(self, *args): return _Cmatrice.Cmatrice_forward(self, *args)
    def backward(self, *args): return _Cmatrice.Cmatrice_backward(self, *args)
    def smoothe(self, *args): return _Cmatrice.Cmatrice_smoothe(self, *args)
    def predictions(self, *args): return _Cmatrice.Cmatrice_predictions(self, *args)
    def derive(self, *args): return _Cmatrice.Cmatrice_derive(self, *args)
    def integre(self, *args): return _Cmatrice.Cmatrice_integre(self, *args)
    def genere(self, *args): return _Cmatrice.Cmatrice_genere(self, *args)
    def read_nf(self, *args): return _Cmatrice.Cmatrice_read_nf(self, *args)
    def __str__(self): return _Cmatrice.Cmatrice___str__(self)
    def __len__(self): return _Cmatrice.Cmatrice___len__(self)
    def ndesc(self): return _Cmatrice.Cmatrice_ndesc(self)
    def __call__(self, *args): return _Cmatrice.Cmatrice___call__(self, *args)
Cmatrice_swigregister = _Cmatrice.Cmatrice_swigregister
Cmatrice_swigregister(Cmatrice)



